name: Build and Upload

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup JAVA 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Cache Maven Packages
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: PlayerVaults
          path: target/PlayerVaults-*.jar